FORMAT: 1A
HOST: http://tools.api/v1

# Tools API

Tools API é uma API simples que possibilida listar, consultar, criar ou deletar ferramentas.

# Group URLs

URLs existentes da API

## Tools [/tools]

### Listar todas ferramentas [GET]

+ Response 200 (application/json)

        [
            {
                id: 1,
                title: "Notion",
                link: "https://notion.so",
                description: "All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ",
                tags: [
                    "organization",
                    "planning",
                    "collaboration",
                    "writing",
                    "calendar"
                ]
            },
            {
                id: 2,
                title: "json-server",
                link: "https://github.com/typicode/json-server",
                description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
                tags: [
                    "api",
                    "json",
                    "schema",
                    "node",
                    "github",
                    "rest"
                ]
            },
            {
                id: 3,
                title: "fastify",
                link: "https://www.fastify.io/",
                description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
                tags: [
                    "web",
                    "framework",
                    "node",
                    "http2",
                    "https",
                    "localhost"
                ]
            }
        ]

### Criar nova ferramenta [POST]

+ Request (application/json)

        {
            {
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
            }
        }

+ Response 201 (application/json)

        

            {
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"],
                "id":5
            }
        
## Deletar ferramenta por ID [/tools/{id}]

+ Parameters
    + id: 1(number, required) - Id da ferramenta

### Deletar ferramenta [DELETE]

+ Response 200

        Headers
                Content-type: application/json

        Body

                {

                }


## Filtrar ferramentas por tag [/tools?tag={tag}]

+ Parameters 
    + tag: node(string, required) - tag que deseja filtrar

### Filtarr ferramenta por tag [GET]

+ Response 200

            [
            {
                id: 2,
                title: "json-server",
                link: "https://github.com/typicode/json-server",
                description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
                tags: [
                    "api",
                    "json",
                    "schema",
                    "node",
                    "github",
                    "rest"
                ]
            },
            {
                id: 3,
                title: "fastify",
                link: "https://www.fastify.io/",
                description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
                tags: [
                    "web",
                    "framework",
                    "node",
                    "http2",
                    "https",
                    "localhost"
                ]
            }
        ]



